spring:
    profiles: teste
    jpa:
        database: POSTGRESQL
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.connection.provider_disables_autocommit: false
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
        hibernate:
            ddl-auto: none
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    datasource:
        username: postgres
        password: postgres
        url: jdbc:postgresql://localhost:5432/compras_online
        driver-class-name: org.postgresql.Driver

server:
    port: 8081
