version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:11.6
    environment:
      - POSTGRES_DB=compras_online
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
